### PR TITLE
NS7 plugin updates

### PR DESCRIPTION
**Pull request by bradmartin**
Updates the android sdk to latest
Updates plugin for NS7 version

Many other changes.

Only issue, is getting the demo apps to run/update and it should be good to go. I think it's the angular module that is causing issues with actually running the demos, but not sure.

### CODE REVIEW

**Comment by bradmartin** [comment]
Plain TS Demo is working now. So the plugin should work, just not sure about the ng module that the plugin ships.

**Comment by bradmartin** [comment]
Both demos are now running NS7 with latest changes 💯

**Comment by bradmartin** [comment]
@sc85 @tillsanders  - any way to get a quick look at this and publish a new major for NS7? Any questions I'm happy to answer or work with to get this done :)

**Comment by tillsanders** [comment]
@bradmartin Thank you very much for your contribution! We will merge your changes into a new branch, update the readme and release an alpha version for NativeScript 7 on npmjs.org. Presumably next week we want to take care of some test cases and maybe a Vue.js demo.

**Comment by bradmartin** [comment]
Feel free to revert back any formatting you prefer, I just dropped in a prettierrc file that I typically use, but if you prefer a different code formatting, I do not have any issues :) so long as the pre-commit hook stays in place so we don't have to worry about spacing/tabs and line breaks 😉

Thanks for merging this.

**Pull request merged**
