### PR TITLE
Upgrade Android native deps and typings

### LINKED ISSUE #8: Upgrade the Android Sentry SDK to 4.1.0 or above
### Which platform(s) does your issue occur on?
- Android 11 (targetSdkVersion 30)
- https://github.com/getsentry/sentry-java/issues/904#issuecomment-772126738

### Please, tell us how to recreate the issue in as much detail as possible. 
There is an issue with the Android Sentry SDK if you use targetSdk 30.
https://github.com/getsentry/sentry-java/issues/904

This nativescript plugin is using the 2.3.1 version of the SDK which is affected by the issue.

Currently Google Play is forcing us to move away from 29 because that is outdated but now with SDK 30 on some devices the app is crashing (not all devices).

Here you can see a list of the devices:
https://github.com/getsentry/sentry-java/issues/904#issuecomment-772126738

Looks like updating to 4.1.0 version of the SDK could fix the issue.

### PR DESCRIPTION
**Pull request by tujlaky**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] All existing tests are passing
- [x] Tests for the changes are included

## What is the new behavior?

Fixes #8

### CODE REVIEW

**Comment by tillsanders** [comment]
Hi @tujlaky,

sorry for the slow response. Our team currently does not have the capabilities to address this issue. All I can do right now is offer to add new collaborators if they are interested or transfer ownership to someone trustworthy. In case of the former, we can obviously still assist with the publishing of packages, but not with reviewing or testing.

Please let me know if I can do anything in that regard to help the project continue.

**Comment by tujlaky** [comment]
Thanks. 

The issue is that in the current state the plugin is not usable anymore on Android devices.
I don't know what would be the solution but in this case I think I will not use this plugin anymore because it is not secure and not maintained.

**Comment by bradmartin** [comment]
Currently testing your branch out in an app @tujlaky - will circle back if it works. I do think one other change is needed according to the sentry documentation on the include.gradle file regarding java 1.8 compat. I added it locally and am testing.

**Comment by bradmartin** [comment]
Can confirm things are working fine @tujlaky @tillsanders 

I'd suggest @tujlaky  adding the java compat to the include.gradle of this plugin mentioned [here by sentry](https://docs.sentry.io/platforms/android/#install). I've done this locally on your fork and it works fine in my app. So we're moving forward with a local pack of your updates for now.

**Comment by bradmartin** [comment]
Coming back, one month later your fork with that gradle file change and all things seem to be working well for us with this plugin @tillsanders any chance of merging and publishing to npm?

**Review by sc85 — APPROVED** [review]

**Comment by tillsanders** [comment]
We tried to release a new version but it seems that our setup is too old (see latest workflow) 😞  I tried to update everything to match the [plugin seed template](https://github.com/NativeScript/plugin-seed) but it quickly became evident that that would require more effort and time than I currently have at my disposal. Especially updating the demos appears to be difficult for someone who hasn't worked with recent versions of NativeScript. If anyone is willing to help, that would be great!

**Comment by bradmartin** [comment]
I can try to do that this week if time allows.

**Comment by nojcc** [comment]
Any update on this?

**Pull request merged**
